export const ServiceData = [
    {
        src: "/img/service/png/vfx.png",
        width: "135px",
        high: "79px",
        alt: "Visual Effects",
        id: 1,
    },
    {
        src: "/img/service/png/layout.png",
        width: "163px",
        high: "79px",
        alt: "Layout",
        id: 2,
    },
    {
        src: "/img/service/png/rendering.png",
        width: "146px",
        high: "58px",
        alt: "Animation",
        id: 3,
    },
    {
        src: "/img/service/png/texture.png",
        width: "176px",
        high: "92px",
        alt: "Color",
        id: 4,
    },
    {
        src: "/img/service/png/storyboard.png",
        width: "152px",
        high: "83px",
        alt: "Rotoscoping",
        id: 5,
    },
    {
        src: "/img/service/png/short.png",
        width: "174px",
        high: "94px",
        alt: "short",
        id: 6,
    },
    {
        src: "/img/service/png/script.png",
        width: "146px",
        high: "70px",
        alt: "script",
        id: 7,
    },
    {
        src: "/img/service/png/development.png",
        width: "196px",
        high: "78px",
        alt: "development",
        id: 8,
    },
    {
        src: "/img/service/png/lighting.png",
        width: "218px",
        high: "97px",
        alt: "lighting",
        id: 9,
    },
    {
        src: "/img/service/png/production.png",
        width: "166px",
        high: "80px",
        alt: "production",
        id: 10,
    },
    {
        src: "/img/service/png/rigging.png",
        width: "111px",
        high: "53px",
        alt: "rigging",
        id: 11,
    },
    {
        src: "/img/service/png/long.png",
        width: "95px",
        high: "55px",
        alt: "long",
        id: 12,
    },
    {
        src: "/img/service/png/model.png",
        width: "199px",
        high: "99px",
        alt: "model",
        id: 13,
    },
    {
        src: "/img/service/png/series.png",
        width: "138px",
        high: "81px",
        alt: "series",
        id: 14,
    },
    {
        src: "/img/service/png/tvc.png",
        width: "97px",
        high: "63px",
        alt: "tvc",
        id: 15,
    },
    {
        src: "/img/service/png/creative.png",
        width: "246px",
        high: "96px",
        alt: "creative",
        id: 16,
    },
    {
        src: "/img/service/png/interlectual.png",
        width: "214px",
        high: "103px",
        alt: "interlectual",
        id: 17,
    },
    {
        src: "/img/service/png/post_pro.png",
        width: "125px",
        high: "57px",
        alt: "post_pro",
        id: 18,
    },
    {
        src: "/img/service/png/composite.png",
        width: "229px",
        high: "88px",
        alt: "composite",
        id: 19,
    },
    {
        src: "/img/service/png/conceptual.png",
        width: "185px",
        high: "91px",
        alt: "conceptual",
        id: 20,
    },
    {
        src: "/img/service/png/animation.png",
        width: "244px",
        high: "116px",
        alt: "animation",
        id: 21,
    },
    {
        src: "/img/service/png/3d.png",
        width: "110px",
        high: "74px",
        alt: "3d",
        id: 22,
    },
    {
        src: "/img/service/png/previs.png",
        width: "136px",
        high: "65px",
        alt: "previs",
        id: 23,
    },
    {
        src: "/img/service/png/pre_pro.png",
        width: "148px",
        high: "73px",
        alt: "pre_pro",
        id: 24,
    },
    {
        src: "/img/service/png/2d.png",
        width: "98px",
        high: "69px",
        alt: "2d",
        id: 25,
    },
];
