export const dataNews = [
    {
        id: 1,
        date: "August 30, 2020",
        title: "Covid Pandemic ของ Big Brain Pictures คว้ารางวัล Best Animated Short สาขา Animation & Visual Effect",
        src: "/img/news/01.webp",
        content: "null",
        to: "https://www.facebook.com/bidc.fest/videos/626999371281434/?redirect=false",
        swap: false,
    },
    {
        id: 2,
        date: "August 27, 2020",
        title: "BidcAward สาขา Animation & Visual Effect Best VFX in TV Commercial",
        src: "/img/news/02.webp",
        content: "null",
        to: "https://www.facebook.com/823379977752236/posts/3281749348581941/?d=n",
        swap: true,
    },
    {
        id: 3,
        date: "September 20, 2019",
        title: "วันนัดรวมตัวของผู้ประกอบการ และผู้สนใจนำงานด้านดิจิทัลคอนเทนต์ไปต่อยอดธุรกิจ ภาคเช้ามีกิจกรรมสนทนาถึงความสำเร็จของกิจกรรมพัฒนาเครือข่าย Digital Content",
        src: "/img/news/03.webp",
        content: "null",
        to: "https://www.thansettakij.com/content/409428#.XXinOw-8VcY.twitter",
        swap: false,
    },
    {
        id: 4,
        date: "February 22, 2018",
        title: "VMware ผู้ให้บริการเทคโนโยลีชั้นนำและบริการระบบเสมือนจริงแบบ Cloud  จัดงานประกาศรางวัลพันธมิตรยอดเยี่ยม ที่สยามสมาคมในพระบรมราชูปถัมป์",
        src: "/img/news/04.webp",
        content: "null",
        to: "#",
        swap: true,
    },
    {
        id: 5,
        date: "January 25, 2018",
        title: "AIS Business Solutions ได้จัดงานสัมมนาในหัวข้อ “AIS Cloud Solutions for Animation Industry” ซึ่งเน้นให้ความรู้เกี่ยวกับเทคโนโลยี พร้อมเจาะลึกเรื่องการนำเทคโนโลยี Cloud มาใช้ประโยชน์ในธุรกิจผู้ผลิต Animation ในเมืองไทย",
        src: "/img/news/05.webp",
        content: "null",
        to: "https://www.facebook.com/AISBusinessSolution/posts/858467487648190",
        swap: false,
    },
    {
        id: 6,
        date: "December 04, 2017",
        title: "อุ๋ย นนทรีย์ - ตั้ม อัจฉรา ถ่ายทอดความประทับใจในภาพยนตร์แอนิเมชัน ของขวัญจากดิน",
        src: "/img/news/06.webp",
        content: "null",
        to: "https://www.bugaboo.tv/watch/354038",
        swap: true,
    },
    {
        id: 7,
        date: "December 4, 2017",
        title: `ทีมผู้สร้างชวนดู "ของขวัญจากดิน" ภาพยนตร์อนิเมชั่นเพื่อคนไทย`,
        src: "/img/news/07.webp",
        content: "null",
        to: "https://www.youtube.com/watch?v=At60iuM6EvE",
        swap: false,
    },
    {
        id: 8,
        date: "November 27, 2017",
        title: "ของขวัญจากดิน แอนิเมชั่นเทิดพระเกียรติตามรอยแนวคิดศาสตร์พระราชา",
        src: "/img/news/08.webp",
        content: "null",
        to: "https://mono29.com/episode/181888.html",
        swap: true,
    },
    {
        id: 9,
        date: "November 24, 2017",
        title: `แอนิเมชั่นเล่าศาสตร์พระราชา "ของขวัญจากดิน"ฉายทางทีวีทั่วประเทศ`,
        src: "/img/news/09.webp",
        content: "null",
        to: "https://www.youtube.com/watch?v=bU5_w4PuH1A",
        swap: false,
    },
    {
        id: 10,
        date: "November 23, 2017",
        title: "แถลงข่าวเปิดตัวภาพยนตร์แอนิเมชั่นเทิดพระเกียรติ “ของขวัญจากดิน”",
        src: "/img/news/10.webp",
        content: "null",
        to: "https://www.youtube.com/watch?v=vRrbwB9I0Zo",
        swap: true,
    },
    {
        id: 11,
        date: "November 23, 2017",
        title: `ม.มหิดล โดย โครงการจัดตั้งศูนย์เศรษฐกิจสร้างสรรค์ จัดแถลงข่าวภาพยนตร์แอนิเมชั่น “ของขวัญจากดิน”`,
        src: "/img/news/11.webp",
        content: "null",
        to: "https://mahidol.ac.th/th/2017/khongkwan-2/",
        swap: false,
    },
    {
        id: 12,
        date: "November 23, 2017",
        title: `แถลงข่าวเปิดตัวภาพยนตร์แอนิเมชั่นเทิดพระเกียรติ “ของขวัญจากดิน"`,
        src: "/img/news/12.webp",
        content: "null",
        to: "https://www.youtube.com/watch?v=vRrbwB9I0Zo",
        swap: true,
    },
    {
        id: 13,
        date: "April 7, 2017",
        title: `ธนาคารกรุงเทพ รับ 2 รางวัลดีเด่น จากสติ๊กเกอร์ไลน์ Blink Blink ในงาน “Bangkok International Digital Content Festival 2017” เตรียมเปิดตัวชุดใหม่รับสงกรานต์`,
        src: "/img/news/13.webp",
        content: "null",
        to: "http://www.moneyandbanking.co.th/new/13824/7/%E0%B8%98%E0%B8%99%E0%B8%B2%E0%B8%84%E0%B8%B2%E0%B8%A3%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E-%E0%B8%A3%E0%B8%B1%E0%B8%9A-2-%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%A7%E0%B8%B1%E0%B8%A5%E0%B8%94%E0%B8%B5%E0%B9%80%E0%B8%94%E0%B9%88%E0%B8%99-%E0%B8%88%E0%B8%B2%E0%B8%81%E0%B8%AA%E0%B8%95%E0%B8%B4%E0%B9%8A%E0%B8%81%E0%B9%80%E0%B8%81%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B9%84%E0%B8%A5%E0%B8%99%E0%B9%8C",
        swap: false,
    },
    {
        id: 14,
        date: "2016",
        title: `เยี่ยมโครงการส่วนพระองค์ สวนจิตรลดา แหล่งทดลองและจุดกำเนิดของโครงการพระราชดำริในพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดชบรมนาถบพิตร`,
        src: "/img/news/14.webp",
        content: "null",
        to: "#",
        swap: true,
    },
    {
        id: 15,
        date: "2016",
        title: `ศึกษาดูงาน “ประเพณีบุญบั้งไฟ” บูชาพญาแถนขอฝน จังหวัดชัยภูมิ`,
        src: "/img/news/15.webp",
        content: "null",
        to: "#",
        swap: false,
    },
    {
        id: 16,
        date: "2016",
        title: `เยี่ยมโครงการโรงเรียนกาสรกสิวิทย์ จังหวัดสระแก้ว โรงเรียนที่ฝึกกระบือให้เชื่องและไถนาได้อย่างชำนาญ`,
        src: "/img/news/16.webp",
        content: "null",
        to: "#",
        swap: true,
    },
    {
        id: 17,
        date: "2016",
        title: `ศึกษาดูงานสถาปัตยกรรมของภาคอีสาน “หมู่บ้านอีสาน จิม ทอมป์สัน ฟาร์ม” จังหวัดนครราชสีมา`,
        src: "/img/news/17.webp",
        content: "null",
        to: "#",
        swap: false,
    },
    {
        id: 18,
        date: "2013",
        title: `Promote Yourself: 24 Brand-New Asian Projects to be Unveiled at 2013 Asian Animation Summit`,
        src: "/img/news/18.webp",
        content: "null",
        to: "http://www.animationinsider.com/2013/11/page/3/",
        swap: true,
    },
];

export const dataNewsUp = [
    {
        id: 1,
        date: "March 16, 2023",
        title: "Big Brain Studio at Hong Kong FILMART 2023",
        src: "/img/news2/01.webp",
        content: `After a pandemic pause, Big Brain Studio was thrilled to be at Hong Kong International Film & TV Market (FILMART) this year. It was a pleasure to meet Mr. JAYAKUMAR P., CEO of Toonz Media Group(IN), to catch up with our co-production project. Our "Hey! Buddy" is on the horizon, something extraordinary is coming your way!`,
        to: "#",
        swap: false,
    },
    {
        id: 2,
        date: "April 27, 2023",
        title: "Welcome Conan O'Brien to Big Brain Studio!",
        src: "/img/news2/02.webp",
        content: `We recently had the honor of hosting a visit from the legendary Conan O'Brien at our studio, and it was truly a delightful experience. Laughter filled the air as we spent a pleasant time together, sharing some good laughs.`,
        to: "",
        swap: true,
    },
    {
        id: 3,
        date: "June 17, 2023",
        title: "Big Brain Studio at Annecy Animation Festival 2023",
        src: "/img/news2/03.webp",
        content: `Big Brain Studio was honored to have been included in the Thailand Pavilion at the esteemed Annecy Animation Festival 2023. It was a delightful experience engaging with talented individuals and studios from across the globe, as we shared and exchanged our creative insights during this exhilarating event. We look forward to reuniting next year!`,
        to: "#",
        swap: false,
    },
    {
        id: 4,
        date: "July 01, 2023",
        title: "Work Hard, Play Hard – Explore Thailand with Big Brain Studio",
        src: "/img/news2/04.webp",
        content: `After some hard work, we're taking a break to enjoy Thailand's beauty, recharge our creative energy, and uncover hidden gems right in our backyard. It's been a blast! We've engaged in lots of fun activities, creating unforgettable memories along the way.`,
        to: "",
        swap: true,
    },
    {
        id: 5,
        date: "June 18, 2023",
        title: "Big Brain Studio at Annecy Animation Festival 2023",
        src: "/img/news2/05.webp",
        content: `Big Brain Studio was honored to have been included in the Thailand Pavilion at the esteemed Annecy Animation Festival 2023. It was a delightful experience engaging with talented individuals and studios from across the globe, as we shared and exchanged our creative insights during this exhilarating event. We look forward to reuniting next year!`,
        to: "#",
        swap: false,
    },
    {
        id: 6,
        date: "June 21, 2023",
        title: "Glad to Host: Armada TMT Studio, the French Embassy, Warner Bros Discovery, and Yomzeo Studio Pay Us a Friendly Visit!",
        src: "/img/news2/06.webp",
        content: `Our studio was delighted to welcome our esteemed guests. We extend our gratitude to Ms. Onmadee 'Cherry' Purapati from TACGA for arranging the visit, which included Mr. Sidi Benlarbi from Armada TMT/Xilam Studio (VN/FR), as well as Mr. Jérémy Segay and Mr. Julien Lacorne from the French Embassy. We also had the pleasure of hosting Mr. Andre Seungwook Lee from Yomzeo (KR/FR), and last but not least, Ms. Carlene Tan from Warner Bros Discovery (SG). We had an amazing time together, and we're eagerly anticipating future collaborative opportunities. Stay tuned for exciting ventures!`,
        to: "",
        swap: true,
    },
    {
        id: 7,
        date: "August 30, 2023",
        title: "Studio Tour Welcomes Our Friend, Hide and Seed",
        src: "/img/news2/07.webp",
        content: `After our quick meet up at Annecy 2023, it was awesome to have Kin Lek Chaw from Hide and Seeds Production (MY) visit our studio. We had a great time chatting about the animation industry and are definitely looking forward to teaming up soon!`,
        to: "#",
        swap: false,
    },
    {
        id: 8,
        date: "September 30, 2023",
        title: "Kre8tif 2023: Latest Project Pitch and Big Brain Studio Showcase at KLCC, Kuala Lumpur",
        src: "/img/news2/08.webp",
        content: `Ker8tif 2023 brought a wave of excitement! We felt incredibly honored to have the opportunity to be a part of elevator pitch session to present our groundbreaking ideas to esteemed judges from leading broadcasters and respected industry experts. The invaluable feedback and insights we received were genuinely enriching. Showcasing our creative journey at our booth was equally delightful. Meeting and connecting with fellow creative minds and exploring potential collaborations was an incredibly positive experience. We are grateful for the memorable time we had in Kuala Lumpur!`,
        to: "",
        swap: true,
    },
];
